### ISSUE TITLE
Final Assignment: Problems with my Plots 

### ISSUE THREAD

**Issue by LinhRamirez** [DeAngelisA/ISSS21#17]
Hi there 

I am working to do the plots in the final assignment, but I am facing some visualizing problems. 

I prepared my data set like this:

```{r}

Suicide_rate_gdp <- Suicide_rate %>%
  rename(country = ï..country, gdp_per_year = gdp_for_year....) %>%
  group_by(country, year, gdp_per_year) %>%
  filter(year >= 1996, suicides_no > 0) %>%
  summarise(suicides_total = sum(suicides_no), pop_total = sum(population)) %>%
  mutate(suicides_per_pop=suicides_total*100/pop_total)

```

My tibble of the data is the following (after cleaning my data set):

![image](https://user-images.githubusercontent.com/91264824/145674982-6af6e5f4-d775-45bb-be24-9643fdef3b47.png)

----
**First Problem:**
Now while trying to do a plot, with my variables gdp_per_year and suicides_total (or even with suicides_per_pop) 

```{r}
ggplot(Suicide_rate_gdp, aes(x=gdp_per_year, y= suicides_per_pop)) +
  geom_point() + geom_smooth(alpha = 0.3, method=lm, se=FALSE, col="blue") + ggtitle("Scatter Plot: Suicides per Population and GDP per Year") + xlab("GDP per Year") + ylab("Suicide Rate per Population")

ggplot(data=Suicide_rate_gdp, aes(x=year, y=suicides_per_pop)) +
  geom_line()+ggtitle("Line Plot: Suicides per Population and Year") + xlab("Year") + ylab("Suicide Rate per Population")

ggplot(Suicide_rate_gdp, aes(x=gdp_per_year, y= suicides_total)) +
  geom_point() + geom_smooth(alpha = 0.3, method=lm, se=FALSE, col="blue") + ggtitle("Scatter Plot: Suicides per Population and GDP per Year") + xlab("GDP per Year") + ylab("Suicide Rate per Population")

ggplot(Suicide_rate_gdp, aes(x=suicides_total, y= gdp_per_year)) +
  geom_point() + geom_smooth(alpha = 0.3, method=lm, se=FALSE, col="blue") + ggtitle("Scatter Plot: Suicides per Population and GDP per Year") + xlab("GDP per Year") + ylab("Suicide Rate per Population")
```

all what comes out is this:
![image](https://user-images.githubusercontent.com/91264824/145675002-613adbc2-1966-4cd6-9810-06a06d505a33.png)

![image](https://user-images.githubusercontent.com/91264824/145674814-0f6af647-3770-4555-a545-cf8266d8bff7.png)

![image](https://user-images.githubusercontent.com/91264824/145674834-e1336343-f136-4e55-ad82-0d03c485fb91.png)

![image](https://user-images.githubusercontent.com/91264824/145674847-d3bc66d1-4d86-4305-a2a9-c5ba139790c4.png)

-----
**And I think it doesn't look good,  I can't see anything specific. I am also confused, as I would like to be able to see in my plot, gdp_per_year, the difference between the countries (like in a legend) and also the year and the suicide rate. By defining my data set, wouldn't it be possible to see these 4 things in my plot? What am I missing? Because I am aware, that I have to include my My independent variable, whcih is in general the GDP per Country per year and my dependent variable is the suicide rate.** 

Or did I do sth wrong with my data? 

Because while trying out the boxplot (not in ggplot) it looked perfect!

```{r}
Suicide_rate_gdp %>% 
  boxplot(suicides_per_pop ~ year, data = ., main="Boxplot of Suicide Rate", ylab = "Suicide Rate per Population", xlab = "Year between 1996 - 2016", col="orange")
grid()
```

![image](https://user-images.githubusercontent.com/91264824/145674885-3dd4facb-30cc-4386-9a62-47e2f98f4a31.png)

------

Or does it has something to do with the type of the variable? Because I found out, that the variable gdp_per_year is **<chr>** and I think (but I am not sure about it), it should be an **<int>**.  So I found out, that we can change it with this code:
But I am confused, as I am not sure how to integrate this change into my tibble / data set. (If this type of variable is the cause of it) 

```{r}
gdp_int <- as.integer("gdp_per_year")
```

**Comment by marcograf1** [comment]
Hi Linh

I guess the problem is that R reads your variable **gdp_per_year** as a character and not as an integer. Check the type of your variables with the **str( )** function, i.e. in your case str(Suicide_rate_gdp).

I would do the following: 
Suicide_rate_gdp <- Suicide_rate %>%
  rename(country = ï..country, gdp_per_year = gdp_for_year....) %>%
  group_by(country, year, gdp_per_year) %>%
  filter(year >= 1996, suicides_no > 0) %>%
  summarise(suicides_total = sum(suicides_no), pop_total = sum(population)) %>%
  mutate(suicides_per_pop=suicides_total*100/pop_total) %>%
# transform gdp_per_year into an integer using the code **variable <- as.integer(variable)** and create the new variable gdp_int
  **mutate(gdp_int = gdp_per_year <- as.integer(gdp_per_year))** **%>%**
# **use select( )** to choose the variables for your new dataframe which contains gdp_int but exlcudes gdp_per_year  
 **select(country, year, **gdp_int**, suicides_total, pop_total, suicides_per_pop)** 

# Finally, check the types of your variables using the **str( ) function** again: gdp_int should be an integer 

Hope it works!
Marco

**Comment by marcograf1** [comment]
Hi Linh

I guess the problem is that R reads your variable **gdp_per_year** as a character and not as an integer.

Check the type of your variables with the **str( )** function, i.e. str(dataset).

Solution: **transform** gdp_per_year into an integer. I would add the following **last two steps (in bold)** to your dataset preparation process:

Suicide_rate_gdp <- Suicide_rate %>%
... %>%
... %>%
... %>%
... %>%
... %>%
**mutate(gdp_new = gdp_old <- as.integer(gdp_old)) %>%** (see comment 1)
**select(country, year, gdp_new, etc.)** (see comment 2)

Comments:

(1) Transform gdp_old (i.e. gdp_per_year) into an integer using the code **variable <- as.integer(variable)** and use **mutate( )** to create the new variable gdp_new which is the transformed gdp_old variable.

(2) Use **select( )** to update your dataset by selecting all of your variables of interest which includes gdp_new but excludes gdp_old.

Finally, check the type of your variables using **str( )** again: gdp_new should be an integer.

Hope it works!
Marco

**Comment by DeAngelisA** [comment]
@LinhRamirez : yes, the cause of the problem is that `gpd_per_year` is of character type and so it is being treated as a factor. @marcograf1, thanks for contributing! Your solution is correct, you need to convert it to numeric. 
However, the code will look like this: 

```r 
Suicide_rate_gdp <- Suicide_rate %>%
  rename(country = ï..country, gdp_per_year = gdp_for_year....) %>%
  group_by(country, year, gdp_per_year) %>%
  filter(year >= 1996, suicides_no > 0) %>%
  summarise(suicides_total = sum(suicides_no), pop_total = sum(population)) %>%
  mutate(suicides_per_pop=suicides_total*100/pop_total, 
              gdp_per_year = as.numeric(gdp_per_year)
)
```

@marcograf1 : note that `mutate(gdp_new = gdp_old <- as.integer(gdp_old))` will not work because it is assigning twice. It should be `mutate(gdp_new = as.integer(gdp_old))` instead. 

Hope this helps!

**Comment by marcograf1** [comment]
@DeAngelisA: Thank you for your response, much appreciated! 
I experienced a similar issue like Linh and I tested my approach which seems to work.
R reads my variable voter_category as a character which I then converted into a new factor variable called voter_cat_new: mutate(voter_cat_new = voter_category <- as.factor(voter_category))

Please see below.

> Read in data
df_nonvoters <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/non-voters/nonvoters_data.csv")


> Create a transformed dataset
df_1 <- df_nonvoters %>% 
  select (ppage, educ, race, gender, income_cat, voter_category) %>% 
  filter(voter_category != "sporadic") %>% 
  filter(!is.na(ppage)) %>%
  mutate(age_group = ifelse(ppage > 53, "old", "young")) %>% 
  move_columns(age_group, .after = ppage) %>%
  mutate(voter_cat_new = voter_category <- as.factor(voter_category))

> Check type of variables
str(df_1)

![grafik](https://user-images.githubusercontent.com/91253864/145977113-1a2f0dcf-19b4-48c3-ab92-89352f5f1c6b.png)

> Create plots
>Univariate visualisation of the dependent variable (categorical): bar chart
plot_1 <- df_1 %>% 
  ggplot(aes(voter_cat_new)) +
  geom_bar()

> Univariate visualisation of the independent variable (continuous): histogram
plot_2 <- df_1 %>% 
  ggplot(aes(ppage)) +
  geom_histogram()

> Bivariate plot (categorical and continuous variable in the same plot): boxplot
plot_3 <- df_1 %>%
  ggplot(aes(ppage, voter_cat_new)) +
  geom_boxplot()

> Infographic using the "patchwork" package
plot_combi <- (plot_1 | plot_2) / plot_3 
plot_combi 

![grafik](https://user-images.githubusercontent.com/91253864/145978440-89e61382-b786-4768-8e7d-29665077b160.png)

**Comment by DeAngelisA** [comment]
OK, everything looks good. I cannot say why that line of code works, but the assignment operator is not expected in a `mutate()` call. You can also run OLS regression with a (numeric!) 0-1 dependent variable. This is called "Linear Probability Model". Despite the disadvantages of occasionally producing impossible predictions (e.g., probabilities > 1), it is very easy to fit and its coefficients can be interpreted as OLS coefficients. You cannot interpret logit coefficients directly, you can only interpret the sign (e.g., `ppage` has a negative effect) and the statistical significance. The rest, you should plot the predicted values to understand the substantial significance. Try calling: `sjPlot::plot_model(logit_model, type = "pred")`.

**Comment by marcograf1** [comment]
@DeAngelisA Thank you very much for your inputs!! 
Yes, in the case of the logit regression the coefficients cannot be interpreted directly. First, I would have to run a logit regression and then let R calculate marginal effects or odds ratio in order to interpret the results of the logit model.

**Comment by LinhRamirez** [comment]
Good Morning Marco and Andrea

Thank you so much for your help. After doing the changes like @DeAngelisA told me, the only problem that occured was, that after changing it into "numeric" I only received NA's in my gdp_per_year column: 

```{r}

Suicide_rate_gdp <- Suicide_rate %>%
  rename(country = ï..country, gdp_per_year = gdp_for_year....) %>%
  group_by(country, year, gdp_per_year) %>%
  filter(year >= 1996, suicides_no > 0) %>%
  summarise(suicides_total = sum(suicides_no), pop_total = sum(population)) %>%
  mutate(suicides_per_pop=suicides_total*100/pop_total, 
              gdp_per_year = as.numeric(gdp_per_year))
```


![image](https://user-images.githubusercontent.com/91264824/146328947-03e87bda-bc45-409c-9c12-d59737a2d5c0.png)


The same thing happened with the code @marcograf1 gave me:

```{r}

Suicide_rate_gdp <- Suicide_rate %>%
  rename(country = ï..country, gdp_per_year = gdp_for_year....) %>%
  group_by(country, year, gdp_per_year) %>%
  filter(year >= 1996, suicides_no > 0) %>%
  summarise(suicides_total = sum(suicides_no), pop_total = sum(population)) %>%
  mutate(suicides_per_pop=suicides_total*100/pop_total, gdp_new = gdp_per_year <- as.integer(gdp_per_year)) %>% select(country, year, gdp_new,suicides_total, pop_total, suicides_per_pop)

```

![image](https://user-images.githubusercontent.com/91264824/146329262-efe42d1d-d676-4d5f-ac09-cef8915732a6.png)

So as.integer and as.numeric generate NA's in my data set. Is it because R is not able to read the numbers which provided the dataset? Because the numbers of GDP had commas.

![image](https://user-images.githubusercontent.com/91264824/146329669-ee081d78-e22d-4712-9a5e-9617f14f70f5.png)

**Comment by DeAngelisA** [comment]
@LinhRamirez : yes, you got the problem. Please remind me to show this in class today. 
The solution would be to remove these commas before converting. 

This code reproduces the error:
```r
library(tidyverse)
tibble(
+   my_var = c("134,234", "104,234")
+ ) %>% 
+   mutate(
+     my_var = as.numeric(my_var)
+   )

# A tibble: 2 x 1
  my_var
   <dbl>
1     NA
2     NA
Warning message:
Problem with `mutate()` column `my_var`.
i `my_var = as.numeric(my_var)`.
i NAs introduced by coercion 
```

This provides a solution using [str_replace()](https://stringr.tidyverse.org/reference/str_replace.html):
```r
> tibble(
+   my_var = c("134,234", "104,234")
+ ) %>% 
+   mutate(
+     my_var = as.numeric(stringr::str_replace(string = my_var, pattern = ",", replacement = ""))
+   )
# A tibble: 2 x 1
  my_var
   <dbl>
1 134234
2 104234
```

**Comment by LinhRamirez** [comment]
Hi Andrea @DeAngelisA 

Thank you, It worked! But with str_replace it did not work, but as soon as I used str_replace_all it worked :) 

So finally the code was: 

```{r}

Suicide_rate_gdp <- Suicide_rate %>%
  rename(country = ï..country, gdp_per_year = gdp_for_year....) %>%
  group_by(country, year, gdp_per_year) %>%
  filter(year >= 1996, suicides_no > 0) %>%
  summarise(suicides_total = sum(suicides_no), pop_total = sum(population)) %>%
  mutate(suicides_per_pop=suicides_total*100/pop_total, gdp_per_year=as.numeric(str_replace_all(string = gdp_per_year, pattern = ",", replacement = "")))
```

Thank you so much for the hint and the help :)
