### ISSUE TITLE
Final Assignment - does anyone else work with an ESS dataset?

### ISSUE THREAD

**Issue by NivesLV** [DeAngelisA/ISSS21#20]
Hi, i know i may be late to the party but this my first issue 
for my FA i work with a dataset from ESS. It comes with a codebook, where i have to find / pick my variables. I have trouble finding all my variables.

I have a sneaking suspicion that I am not doing myself any favours with this dataset. Does anyone also work with ESS? 

Thank you
[Codebook.pdf](https://github.com/DeAngelisA/ISSS21/files/7740809/Codebook.pdf)
!

**Comment by katerynamyskova** [comment]
Hi Nives,

I am also working with ESS dataset. As to your question, yes, it’s going to be a royal pain to select (but first find!) your variables of interest in the codebook. 

What helped me was constantly going back and forth between the table of contents and the corresponding pages. I haven’t really found any other way around it.

Plus, as a friendly warning: lots of ESS variables are very unclean and weirdly encoded, so you’ll need to spend quite some time reformatting that if you end up with such variables. In any case, this won’t be an easy job with ESS, so don’t get too optimistic; but in the end I’d say it’s worth working with it :)

**Comment by NivesLV** [comment]
Thank you for your inputs Kateryna! 
"Nice" to hear that it's not just me with ESS :) 
I have found two or three more in the meantime -> it pays off!

**Comment by NivesLV** [comment]
also googling on finding variables in ESS codebooks helped aloot!

**Comment by DeAngelisA** [comment]
@NivesLV : ESS is among the largest comparative surveys in the world. So yes, this can be quite challenging as you are dealing with one of the best and most comprehensive data sources in political sociology. I advise you to act smart: 1. focus on 1/2 models (e.g. if you want to investigate the relationship between media and politics, just check out the modules "media" and "politics"; 2. pick a few variables and keep in mind that the goal of the final assignment is to show statistical proficiency, not to make a full-fledged and scientifically sound investigation. 3. Since you are taking the time to familiarize yourself with ESS, I recommend using it also for future seminar papers and for the thesis. This dataset is a gold mine, you have many countries and years to explore.
